export const DummyNearPets = [
  {
    cardNumber: 1,
    src: '/mock/home/nearpet_thumbnail.jpg',
    tags: ['수컷', '6개월 이하', '임보중', '배변훈련 완료', '타 동물 친화'],
    isLiked: false,
    petData: { lost_pet_id: 1, name: '세바스찬' },
  },
  {
    cardNumber: 2,
    src: '/mock/home/nearpet_thumbnail.jpg',
    tags: [
      '어린이 친화',
      '기본 훈련 완료',
      '중성화 완료',
      '8~18kg',
      '기본 훈련 완료',
    ],
    isLiked: false,
    petData: { lost_pet_id: 2, name: '덕구' },
  },
  {
    cardNumber: 3,
    src: '/mock/home/nearpet_thumbnail.jpg',
    tags: ['암컷', '낯가림', '단모', '중성화 완료', '8살 이상'],
    isLiked: false,
    petData: { lost_pet_id: 3, name: '상추' },
  },
  {
    cardNumber: 4,
    src: '/mock/home/nearpet_thumbnail.jpg',
    tags: [
      '어린이 친화',
      '산책 가능',
      '중성화 완료',
      '8~18kg',
      '기본 훈련 완료',
    ],
    isLiked: false,
    petData: { lost_pet_id: 4, name: '제니퍼' },
  },
  {
    cardNumber: 5,
    src: '/mock/home/nearpet_thumbnail.jpg',
    tags: ['수컷', '6개월 이하', '임보중', '배변훈련 완료', '타 동물 친화'],
    isLiked: false,
    petData: { lost_pet_id: 5, name: '세바스찬' },
  },
  {
    cardNumber: 6,
    src: '/mock/home/nearpet_thumbnail.jpg',
    tags: [
      '어린이 친화',
      '기본 훈련 완료',
      '중성화 완료',
      '8~18kg',
      '기본 훈련 완료',
    ],
    isLiked: false,
    petData: { lost_pet_id: 6, name: '덕구' },
  },
  {
    cardNumber: 7,
    src: '/mock/home/nearpet_thumbnail.jpg',
    tags: ['암컷', '낯가림', '단모', '중성화 완료', '8살 이상'],
    isLiked: false,
    petData: { lost_pet_id: 7, name: '상추' },
  },
  {
    cardNumber: 8,
    src: '/mock/home/nearpet_thumbnail.jpg',
    tags: [
      '어린이 친화',
      '산책 가능',
      '중성화 완료',
      '8~18kg',
      '기본 훈련 완료',
    ],
    isLiked: false,
    petData: { lost_pet_id: 8, name: '제니퍼' },
  },
  {
    cardNumber: 9,
    src: '/mock/home/nearpet_thumbnail.jpg',
    tags: ['수컷', '6개월 이하', '임보중', '배변훈련 완료', '타 동물 친화'],
    isLiked: false,
    petData: { lost_pet_id: 9, name: '세바스찬' },
  },
  {
    cardNumber: 10,
    src: '/mock/home/nearpet_thumbnail.jpg',
    tags: [
      '어린이 친화',
      '기본 훈련 완료',
      '중성화 완료',
      '8~18kg',
      '기본 훈련 완료',
    ],
    isLiked: false,
    petData: { lost_pet_id: 10, name: '덕구' },
  },
  {
    cardNumber: 11,
    src: '/mock/home/nearpet_thumbnail.jpg',
    tags: ['암컷', '낯가림', '단모', '중성화 완료', '8살 이상'],
    isLiked: false,
    petData: { lost_pet_id: 11, name: '상추' },
  },
  {
    cardNumber: 12,
    src: '/mock/home/nearpet_thumbnail.jpg',
    tags: [
      '어린이 친화',
      '산책 가능',
      '중성화 완료',
      '8~18kg',
      '기본 훈련 완료',
    ],
    isLiked: false,
    petData: { lost_pet_id: 12, name: '제니퍼' },
  },
];
