export const DummyNearPets = [
  {
    cardNumber: 50,
    src: '/mock/home/nearpet_thumbnail.jpg',
    tags: ['18kg 이상', '중성화 완료', '타동물 친화'],
    isLiked: false,
    petData: { lost_pet_id: 50, name: '세바스찬' },
  },
  {
    cardNumber: 49,
    src: '/mock/home/nearpet_thumbnail.jpg',
    tags: ['암컷', '18kg 이상', '중성화 완료', '6개월 이하', '7개월~2살'],
    isLiked: false,
    petData: { lost_pet_id: 49, name: '[서울]-나-200-400660-43444' },
  },
  {
    cardNumber: 52,
    src: '/mock/home/nearpet_thumbnail.jpg',
    tags: ['암컷', '8kg 미만', '접종 완료'],
    isLiked: false,
    petData: { lost_pet_id: 52, name: '[서울]-가-102-388273-77462' },
  },
  {
    cardNumber: 62,
    src: '/mock/home/nearpet_thumbnail.jpg',
    tags: ['암컷', '8kg 미만', '접종 완료'],
    isLiked: false,
    petData: { lost_pet_id: 62, name: '두부' },
  },
  {
    cardNumber: 57,
    src: '/mock/home/nearpet_thumbnail.jpg',
    tags: ['암컷', '8kg 미만', '기본훈련 완료'],
    isLiked: false,
    petData: { lost_pet_id: 57, name: '[서울]-바-180-239685-64795' },
  },
  {
    cardNumber: 51,
    src: '/mock/home/nearpet_thumbnail.jpg',
    tags: [
      '6개월 이하',
      '8kg 미만',
      '접종 완료',
      '기본훈련 완료',
      '타동물 친화',
    ],
    isLiked: false,
    petData: { lost_pet_id: 51, name: '딸기' },
  },
  {
    cardNumber: 55,
    src: '/mock/home/nearpet_thumbnail.jpg',
    tags: ['수컷', '중성화 완료', '타동물 친화'],
    isLiked: false,
    petData: { lost_pet_id: 55, name: '우유' },
  },
  {
    cardNumber: 61,
    src: '/mock/home/nearpet_thumbnail.jpg',
    tags: ['수컷', '중성화 완료', '기본훈련 완료'],
    isLiked: false,
    petData: { lost_pet_id: 61, name: '초코' },
  },
  {
    cardNumber: 60,
    src: '/mock/home/nearpet_thumbnail.jpg',
    tags: ['수컷', '중성화 완료', '기본훈련 완료'],
    isLiked: false,
    petData: { lost_pet_id: 60, name: '해피' },
  },
  {
    cardNumber: 100,
    src: '/mock/home/nearpet_thumbnail.jpg',
    tags: ['수컷', '18kg 이상', '중성화 완료', '장모', '타동물 친화'],
    isLiked: false,
    petData: { lost_pet_id: 100, name: '흰둥이' },
  },
  {
    cardNumber: 59,
    src: '/mock/home/nearpet_thumbnail.jpg',
    tags: ['수컷', '기본훈련 완료', '중성화 완료'],
    isLiked: false,
    petData: { lost_pet_id: 59, name: '[서울]-가-180-745673-15232' },
  },
  {
    cardNumber: 58,
    src: '/mock/home/nearpet_thumbnail.jpg',
    tags: ['수컷', '중성화 완료', '접종 완료'],
    isLiked: false,
    petData: { lost_pet_id: 58, name: '누룽지' },
  },
];
